### ISSUE TITLE
Translate mining documentation into one of the following community languages (4 bounties available)

### ISSUE THREAD

**Issue by blockstackers** [blockstackers/testnet-community-bounties#3]
Translate this mining documentation [link] into one of the following languages listed below:

- [ ] Chinese
- [ ] Spanish
- [ ] Turkish
- [ ] Korean

- Quick translations using simple tools like Google Translate will not be accepted. The accuracy and quality of your translation will be checked. 
- We recommend using https://www.sigle.io/ but you may publish your translation on the platform that works best for you.
- **Please submit links to your translations in the comments below.**

A $75 bounty will be awarded to each of the participants responsible for the highest quality Chinese, Spanish, Turkish, and Korean translations. Accuracy and quality of translations will be considered when selecting winners.

**Judging & Deadline:** Winners will be determined by a member of the PBC growth team, with input from Testnet Ambassadors, by the end of Neon (phase 1).

**Comment by lesterli** [comment]
@blockstackers the documents link is missing?

**Comment by blockstackers** [comment]
> @blockstackers the documents link is missing?

Hey @lesterli this bounty will be updated with documentation as soon as it goes up.
